indexes = [
    "uncompensated open-loop nominator", 
    "uncompensated open-loop denominator", 
    "uncompensated closed-loop denominator", 
    "uclp 0", 
    "uclp 1", 
    "uclp 2", 
    "PO max", 
    "Ts max", 
    "c min", 
    "phase deficiency max", 
    "sigma_d min", 
    "pd", 
    "pd phase", 
    "new c", 
    "new PO", 
    "new Ts", 
    "required additional phase", 
    "Gc-z", 
    "Gc-p", 
    "Gc-k", 
    "compensated closed-loop nominator", 
    "compensated closed-loop denominator", 
    "compensated closed-loop zeros", 
    "compensated closed-loop poles"
]